version: '3.8'

services:
  feedback-service:
    build: .
    container_name: feedback-service
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
    volumes:
      - .:/app
      - sqlite_data:/app/data
    env_file:
      - .env
    restart: unless-stopped

volumes:
  sqlite_data: